# commented configuration options are the result when using hatch instead of setuptool
[project]
name = "pixcap65_DOMI1279"
version = "0.1.0-dev4"
description = "Host software for the PixCap65 chip control system based on MIO2 + GPAC hardware."
authors = [
    { name = "Hans Krüger", email = "krueger@physik.uni-bonn.de" },
]
maintainers = [
    { name = "Yannick Dieter", email = "dieter@physik.uni-bonn.de" },
    { name = "Dominik Fischer", email = "s6dkfisc@uni-bonn.de" },
]
license = "Apache-2.0"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=2.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy < 2; python_version < '3'",
    "numpy < 2.3; python_version > '3' and python_version < '3.11'",
    "numpy>=2.3; python_version >= '3.11'",
    "tables>=3.0",
    "pyyaml",
    "ruamel-yaml",
    "bitarray<=1.9.0; python_version < '3'",
    "bitarray>=3.4.0; python_version >= '3.5'",
    "bitarray; python_version < '3.5' and python_version >= '3'",
    "coloredlogs",
    # these declaration is only for the package index!
    "basil-daq <= 3.2.0.dev0 ; python_version >= '3.7'",
    # only to be used for the installations and not for defining the dependency for the package index! (Could not use uv then)
    # "basil-daq @ ../basil-pixcap",
    # "basil-daq @ git+https:////github.com/SiLab-Bonn/basil.git@502a999eb5075e04850f7a481d2668726583c290 ; python_version >= '3.9'",
    # "basil-daq==3.1.0; platform_system == 'Windows' or python_version < '3.9'",
    "tqdm",
]

[project.urls]
Homepage = "https://github.com/SiLab-Bonn/pixcap65/"
Issues = "https://github.com/SiLab-Bonn/pixcap65/issues/"
source = "https://github.com/SiLab-Bonn/pixcap65/"
# no documentation present.

[project.optional-dependencies]
dut = [
    "pyserial",
    "pyvisa ; python_version > '3.5'",
    "pyusb",
    "pysilibusb"
]
advanced = [
    "iminuit>2.30.0; python_version >= '3.9'",
    "iminuit ; python_version < '3.9'",
    "kafe2>2.10.0; python_version >= '3.7'",
    "kafe2 ; python_version < '3.7'",
    "scipy>=1.15.0; python_version >= '3.10'",
    "scipy ; python_version < '3.10'",
    "jacobi ; python_version >= '3.6'",
    "findiff",
    "numba_stats ; python_version >= '3.6'",
    "numba ; python_version > '3.9'"
]
visualization = [
    "pyqt5",
    "vitables",
    "matplotlib<=3.10.9",
    "pycairo",
    "mpld3"
]
docs = [
    "sphinxcontrib-blockdiag",
    "sphinx_rtd_theme",
    "bitarray",
    "pyyaml",
    "setuptools",
    "pkg-resources-backport ; python_version >= '3.9'",
    "myst-parser ; python_version >= '3.6'",
]


# configuration of different build systems which could be used interchangebly!
[build-system]
requires = ["setuptools >= 77.0.3", "hatchling >= 1.26", "uv_build >= 0.11.7, <0.12.0"]
# build-backend = "setuptools.build_meta"
# build-backend = "hatchling.build"
build-backend = "uv_build"

# setuptools configuration
[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
pixcap65.device = ["*.bit"]
device = ["*.bit"]

[tool.setuptools.exclude-package-data]
pixcap65 = [".gitattributes", ".gitignore", "**.h5"]

[tool.setuptools.packages.find]
include = ["pixcap65*", "device*"]
exclude = ["tests", "data_local", "Data", "doc", "**full_analysis", "**.h5", "**.pdf", "legacy"]

# hatch configuration
[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
directory = "out"
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
# the wheel target will determine the editable installs
packages = ["pixcap65"]

[tool.hatch.build.targets.sdist]
exclude = [
    "*.h5",
    "*.pdf",
    "**/full_analysis.py",
    "/.github",
    "/.venv",
    "/.qodana",
    "/.vscode",
    "/.build",
    "/Combination Plots",
    "/data_local",
    "/dist",
    "/dist-uv",
    "/Fit References",
    "/out",
    "/.gitignore"
]

[tool.hatch.envs.hatch-build]
installer = "pip"

[tool.uv]
package = false

[tool.uv.sources]
basil-daq = { path = "../basil-pixcap", editable = true }
smoda-fitter = { path = "../Smoda_2025_Final_Project_Temp", editable = true }

[tool.uv.build-backend]
module-name = "pixcap65"
module-root = ""
namespace = true
data = { data = "pixcap65/device" }
source-exclude = ["doc", "Data", "data_local"]

[dependency-groups]
modelling = [
    "iminuit>=1.4.9",
    "numdifftools>=0.9.41",
    "numpy>=1.16.6",
    "scikit-learn>=0.21.0",
]
