# ----------------------------------------------------------
#  Copyright (c) 2026. SiLab, Institute of Physics, University of Bonn.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------
"""
Implementations of some commonly used measurement routines.
For further measurement routines (in particular more advanced/enhanced ones it might be necessary to implement your
own measurement classes.

If the requirements for the scan configuration could not be fullfilled by this module, it is necessary to provide your
own implemetnation.
"""

import argparse
import logging
import numpy as np
import shutil
import time

from pixcap65.pixcap.pixcap65_measurement import ScanConfigurationKeys
from pixcap65.utils import PixCapSetup, PixcapMeasurements

MAXIMUM_CV_FREQ = 4.1
CV_FREQ_STEP = 1
HV_STEP = 0.25
MAXIMUM_HV_VOLTAGE = 174.1
MAXIMUM_FULL_SCAN_FREQ = 6.1
FULL_SCAN_FREQ_STEP = 0.25
MAXIMUM_INTER_PIX_FREQ = 4.1
INTER_PIX_FREQ_STEP = 0.25


def release_lock():
    """
    Release the lock and deinitialize the acquired lock to clear memory and prevent leakage of semaphore objects
    outside the process.
    """
    global lock
    if lock is not None:
        lock.acquire()
        lock.release()
        del lock
        lock = None

def get_lock():
    """
    Get a lock to synchronize the access to the scan configuration applied to make the script functions thread-safe.
    The lock will be defined as a global module level constant and needs correct handling when the thread or process
    ends.
    :return: acquired lock. (not already acquired but initialized)
    """
    global lock
    if lock is None:
        import threading
        import atexit
        lock = threading.RLock()
        atexit.register(release_lock)

    return lock


lock = None

# configuration of scan parameter used as the base line for all the implemented measurement interfaces.
scan_configuration = {
    'start_column': 0,
    'stop_column': 40,
    'start_row': 0,
    'stop_row': 41,

    'Vin': 1.0,  # input voltage in V
    'frequency_range': np.arange(1, 6.1, 0.5),  # frequency sweep in MHz
    # 'bias_range': -1 * np.geomspace(1, 80, 25),
    # 'bias': -80.0,   # bias voltage to apply in V
    'bias_limit': 0.0000006,
    'bias_sense_range': 0.000001,
    'bias_hv_limit': 0.0000006,

    'data_path': "Thesis/ATLAS_ITk/X1/Test",
    "out_file_mode": "append",
}


def perform_initial_total_measurement(cli_args):
    """
    perform_initial_total_measurement(cli_args)

    @author: Dominik Fischer
    last update: 2026-08-28

    Initializes the setup for a total cap measurement and performs one without applying any bias voltage.
    After completing the measurement a backup of the output file will be created by appending `_1`.

    :param cli_args: namespace of the command-line arguments provided. The namespace could be generated by :py:mod:`argparse`.
        Otherwise a object with similar attributes needs to be provided.
    """
    global scan_configuration
    with get_lock():
        scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS] = 40
        scan_configuration[ScanConfigurationKeys.FREQUENCY_RANGE] = np.arange(1, cli_args.maximum_full_scan_freq, cli_args.full_scan_freq_step)

    if cli_args.total_unbiased:
        print("Will perform the unbiased total cap scan.")
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.TOTAL_CAPACITANCE) as pix:
            pix.pixcap.frequency_settling = cli_args.freq_settle
            # depending on the setup binary readout will not work. Not an issue as the binary readout is only used if the dut configuration file suggests that the smu supports this mode.
            with pix.binary_readout_mode() as binary_pix:
                binary_pix.scan(data_group_spec="unbiased_full")

    with get_lock():
        del scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS]
        try:
            time.sleep(cli_args.wait)
            if cli_args.total_unbiased:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_1.h5"))
        except:
            pass


def perform_iv_measurement(cli_args):
    """
    perform_iv_measurement(cli_args)

    @author: Dominik Fischer
    last update: 2026-08-28

    Initializes the setup for an investigation of the leakage currents dependence on the applied voltage.
    For this measurement the sensor is to be operated in reverse bias.
    For this measurement where only the leakage currents are measured it is encouraged to use multiple current
    measurements to enhance the overall accuracy of the results.
    After completing the measurement a backup of the output file will be created by appending `_2`.

    :param cli_args: namespace of the command-line arguments provided. The namespace could be generated by :py:mod:`argparse`.
        Otherwise a object with similar attributes needs to be provided.
    """
    global scan_configuration
    with get_lock():
        scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE] = -1 * np.arange(0, cli_args.maximum_hv_voltage, cli_args.hv_step)
        scan_configuration[ScanConfigurationKeys.BIAS_AVERAGE_MEASUREMENTS] = 20
        assert np.all(0 >= scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE])
    if cli_args.iv_flag:
        print("Perform IV Scan.")
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.TOTAL_CAPACITANCE) as pix:
            pix.bias_scan(data_group_spec="I_V_Characteristic")

    with get_lock():
        del scan_configuration[ScanConfigurationKeys.BIAS_AVERAGE_MEASUREMENTS]
        try:
            time.sleep(cli_args.wait)
            if cli_args.iv_flag:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_2.h5"))
        except:
            pass


def perform_coarse_cv_scan(cli_args, hv_range):
    """
    perform_coarse_cv_scan(cli_args, hv_range)

    @author: Dominik Fischer
    last update: 2026-08-28

    Implements a coarse cv scan suitable for only a few pixel to decide on the spacings to be used for a more fine scan
    in order to determine the depletion voltage on a per pixel level.

    The voltages of the CV characterization are to be supplied by the commandline arguments Namespace object.
    For each of these voltages (should be a coarse grid) the few selected pixel are scanned for their capacitances.
    The switching frequencies used for determining the capacitances are to be supplied by the cli namespace.

    Only reversed bias voltage grids are allowed.
    After completing the measurement a backup of the output file will be created by appending `_3`.


    :param cli_args: namespace of the command-line arguments provided. The namespace could be generated by :py:mod:`argparse`.
        Otherwise a object with similar attributes needs to be provided.
    :param hv_range: grid of the reversed bias voltage (with correct sign) to use for the characterization.
    """
    global scan_configuration

    with get_lock():
        scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE] = hv_range
        scan_configuration.update(start_row=20, stop_row=25, start_column=20, stop_column=25)
        scan_configuration[ScanConfigurationKeys.FREQUENCY_RANGE] = np.arange(1, cli_args.maximum_cv_freq, cli_args.cv_freq_step)
        if ScanConfigurationKeys.BIAS_AVERAGE_MEASUREMENTS in scan_configuration:
            del scan_configuration[ScanConfigurationKeys.BIAS_AVERAGE_MEASUREMENTS]
        if ScanConfigurationKeys.AVERAGE_MEASUREMENTS in scan_configuration:
            del scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS]
        assert np.all(scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE] < 0)

    if cli_args.cv_general_flag and cli_args.cv_coarse_flag:
        print("Perform the coarse bias scan")
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.TOTAL_CAPACITANCE) as pix:
            pix.combined_bias_cv_scan(data_group_spec="C_V_Characteristic")

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.cv_general_flag and cli_args.cv_coarse_flag:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_3.h5"))
        except:
            pass


def perform_fine_cv_scan(cli_args, hv_range):
    """
    perform_fine_cv_scan(cli_args, hv_range)

    @author: Dominik Fischer
    last update: 2026-08-28

    Implements a fine-grain cv scan suitable for a large pixel matrix
    in order to determine the depletion voltage on a per pixel level.

    The voltages of the CV characterization are to be supplied by the parameters to allow more flexibility with the spacing.
    For each of these voltages selected pixel are scanned for their capacitances.
    The switching frequencies used for determining the capacitances are to be supplied by the cli namespace.
    The scanned pixels are fixed from row 10 to row 35 and column 10 to column 35.

    Only reversed bias voltage grids are allowed.
    After completing the measurement a backup of the output file will be created by appending `_4`.

    :param cli_args: namespace of the command-line arguments provided. The namespace could be generated by :py:mod:`argparse`.
        Otherwise a object with similar attributes needs to be provided.
    :param hv_range: grid of the high voltages to use for the measurement.
    """
    global scan_configuration

    with get_lock():
        scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE] = hv_range
        scan_configuration.update(start_row=10, stop_row=35, start_column=10, stop_column=35)
        scan_configuration[ScanConfigurationKeys.FREQUENCY_RANGE] = np.arange(1, cli_args.maximum_cv_freq, cli_args.cv_freq_step)
        assert np.all(scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE] < 0)

    if cli_args.cv_general_flag and cli_args.cv_fine_flag:
        print("Perform the fine bias scan")
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.TOTAL_CAPACITANCE) as pix:
            pix.frequency_settling = cli_args.freq_settle
            pix.combined_bias_cv_scan(data_group_spec="C_V_Characteristic_refined")

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.cv_general_flag and cli_args.cv_fine_flag:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_4.h5"))
        except:
            pass


def perform_biased_total_cap(cli_args):
    """
    perform_biased_total_cap(cli_args)

    @author: Dominik Fischer
    last update: 2026-08-28

    Initializes the setup for a total cap measurement and performs one with applying a bias voltage
    suitable to completely deplete the investigated sensor.
    The actually applied bias voltage must be in reversed bias and sufficient to fully deplete the sensor.
    After completing the measurement a backup of the output file will be created by appending `_5`.

    :param cli_args: namespace of the command-line arguments provided. The namespace could be generated by :py:mod:`argparse`.
        Otherwise a object with similar attributes needs to be provided.
    """
    global scan_configuration
    with get_lock():
        if ScanConfigurationKeys.BIAS_VOLTAGE_RANGE in scan_configuration:
            del scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_RANGE]
        scan_configuration.update(start_row=1, stop_row=41, start_column=0, stop_column=40, bias=-1 * cli_args.hv_voltage,
                                  average_measurements=40)
        scan_configuration[ScanConfigurationKeys.FREQUENCY_RANGE] = np.arange(1, cli_args.maximum_full_scan_freq, cli_args.full_scan_freq_step)
        scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS] = 30
        assert scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_SINGLE] <= 0

    if cli_args.depleted_flag:
        print("Perform the full over-depleted scan.")
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.TOTAL_CAPACITANCE) as pix:
            pix.pixcap.frequency_settling = cli_args.freq_settle
            with pix.binary_readout_mode() as binary_pix:
                binary_pix.scan(data_group_spec="biased_{}_V_full".format(cli_args.hv_voltage))

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.depleted_flag:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_5.h5"))
        except:
            pass
        finally:
            del scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS]


def perform_inter_pix_scan(cli_args):
    """
    perform_inter_pix_scan(cli_args)

    @author: Dominik Fischer
    last update: 2026-08-28

    Implements two inter-pixel capacitance scans.
    In both cases the the summed-up contributions of all eight neighbouring pixels to the inter-pixel capacitance is
    measured.

    The arguments must be submitted by the commandline arguments namespace object.
    These will also define whether only (and which one) or both inter-pixel capacitance measurements should be performed.
    The first inter-pixel capacitance measurement will be performed without applying a bias voltage.
    The second one will apply a reversed bias voltage.
    The bias voltage should be chosen sufficiently large to fully deplete the investigated sensor.


    :param cli_args: namespace of the command-line arguments provided. The namespace could be generated by :py:mod:`argparse`.
        Otherwise a object with similar attributes needs to be provided.
    """
    global scan_configuration

    with get_lock():
        scan_configuration[ScanConfigurationKeys.FREQUENCY_RANGE] = np.around(np.arange(1, cli_args.maximum_inter_pix_freq, cli_args.inter_pix_freq_step), 2)
        scan_configuration.update(start_row=2, stop_row=38, start_column=1, stop_column=38)
        if ScanConfigurationKeys.BIAS_VOLTAGE_SINGLE in scan_configuration:
            del scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_SINGLE]

    if cli_args.inter_pix_cap:
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.INTER_CAPACITANCE) as pix:
            with pix.enhanced_readout_mode():
                pix.frequency_settling = cli_args.freq_settle
                pix.scan(data_group_spec="inter_unbiased_full")

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.inter_pix_cap:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_6.h5"))
        except:
            pass
        finally:
            scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_SINGLE] = -1 * cli_args.hv_voltage
            assert scan_configuration[ScanConfigurationKeys.BIAS_VOLTAGE_SINGLE] <= 0

    if cli_args.inter_pix_cap:
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=PixcapMeasurements.INTER_CAPACITANCE) as pix:
            with pix.enhanced_readout_mode():
                pix.frequency_settling = cli_args.freq_settle
                pix.scan(data_group_spec="inter_biased_M_{}_V_full_Extended".format(cli_args.hv_voltage))

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.inter_pix_cap:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_7.h5"))
        except:
            pass
        finally:
            scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS] = 15

    if cli_args.inter_pix_cap and cli_args.inter_pix_cap_sides:
        from pixcap65.pixcap_65_inter_cap import Pixcap65InterCapSides
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=Pixcap65InterCapSides) as pix:
            with pix.enhanced_readout_mode():
                pix.frequency_settling = cli_args.freq_settle
                pix.scan(data_group_spec="inter_biased_M_{}_V_full__sides".format(cli_args.hv_voltage))

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.inter_pix_cap:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_7-1.h5"))
        except:
            pass

    if cli_args.inter_pix_cap and cli_args.inter_pix_cap_tops:
        from pixcap65.pixcap_65_inter_cap import Pixcap65InterCapTops
        with PixCapSetup(scan_configuration, cli_args.output_file, measurement=Pixcap65InterCapTops) as pix:
            with pix.enhanced_readout_mode():
                pix.frequency_settling = cli_args.freq_settle
                pix.scan(data_group_spec="inter_biased_M_{}_V_full__tops".format(cli_args.hv_voltage))

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.inter_pix_cap:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_7-2.h5"))
        except:
            pass

    if cli_args.inter_pix_cap and cli_args.inter_pix_cap_diagonals:
        from pixcap65.pixcap_65_inter_cap import Pixcap65InterCapDiagonals
        with PixCapSetup(scan_configuration, cli_args.output_file,
                         measurement=Pixcap65InterCapDiagonals) as pix:
            with pix.enhanced_readout_mode():
                pix.frequency_settling = cli_args.freq_settle
                pix.scan(data_group_spec="inter_biased_M_{}_V_full___diagonals".format(cli_args.hv_voltage))

    with get_lock():
        try:
            time.sleep(cli_args.wait)
            if cli_args.inter_pix_cap:
                shutil.copyfile(cli_args.output_file, cli_args.output_file.replace(".h5", "_7-3.h5"))
        except:
            pass
        finally:
            if ScanConfigurationKeys.AVERAGE_MEASUREMENTS in scan_configuration:
                del scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS]


def main():
    """
    main or commandline tool for performing measurements with pixcap65 from the console.

    @author: Dominik Fischer
    last update: 2026-08-28

    A general advice to get information about the usage is to execute `python -m pixcap65.measurements --help`.
    """
    # one setup trial per measurement
    argument_parser = argparse.ArgumentParser("Pixcap65 Measurements")
    general_argument_group = argument_parser.add_argument_group("General arguments")
    selection_argument_group = argument_parser.add_argument_group("Selection arguments")
    selection_argument_group.add_argument("-u", "--unbiased", action='store_true', dest='total_unbiased', help='Unbiased total capacitance measurement to perform')
    selection_argument_group.add_argument("-i", "--inter-pix", action='store_true', dest='inter_pix_cap', help='Measure the interpixel capacitances by both methods.')
    selection_argument_group.add_argument("--inter-pix-sides", action='store_true', dest='inter_pix_cap_sides', help='Measure the interpixel capacitances in the completely biased state but only the contribution the two horizontal neighbours.')
    selection_argument_group.add_argument("--inter-pix-tops", action='store_true', dest='inter_pix_cap_tops',
                                          help='Measure the interpixel capacitances in the completely biased state but only the contribution the two vertical neighbours.')
    selection_argument_group.add_argument("--inter-pix-diagonals", action='store_true', dest='inter_pix_cap_diagonals',
                                          help='Measure the interpixel capacitances in the completely biased state but only the contribution the four neighbours on the diagonals..')
    cv_argument_group = argument_parser.add_argument_group("C-V-Characterization options")
    cv_argument_group.add_argument("-c", "--c-v-general", action='store_true', dest='cv_general_flag', help='Enable the measurement of the CV Characteristic')
    selection_argument_group.add_argument('--iv', action='store_true', dest='iv_flag', help='Enable the measurement of the IV Characteristic')
    general_argument_group.add_argument("--wait", action='store', dest='wait', help='Wait before backing the measurement file up and stepping to the next measurement in the procedure.', default=5, type=float)
    general_argument_group.add_argument("--hv_bias", action='store', dest='hv_voltage', default=80, type=float, help='HV bias voltage to use for biased measurements.')
    general_argument_group.add_argument('--settling', action='store', dest='freq_settle', default=0.3, type=float, help='Settling time for the frequency before measurements.')
    selection_argument_group.add_argument('--depleted', action='store_true', dest='depleted_flag', help='Full sensor scan in over-depleted state.')
    cv_argument_group.add_argument('--c-v-fine', action='store_true', dest='cv_fine_flag', help='Enable the fine grid measurement of the CV Characteristic.')
    cv_argument_group.add_argument('--c-v-coarse', action='store_true', dest='cv_coarse_flag', help='Enable the coarse grid measurement of the CV Characteristic.')
    general_argument_group.add_argument('-v', '--verbose', action='store_true', dest='verbose_flag', help='Enable verbose mode.')

    scan_argument_group = argument_parser.add_argument_group("Scan Parameters")
    scan_argument_group.add_argument('-o', '--output', action='store', dest='output_file', help='Output file name. (default: %(default)s)', default="data/X1_24_Renew_Scan.h5")
    scan_argument_group.add_argument('--max-freq-full', action='store', type=float, default=MAXIMUM_FULL_SCAN_FREQ, dest='maximum_full_scan_freq', help='Maximum switching-frequency to use for a full total capacitance scan. (default: %(default)s)')
    scan_argument_group.add_argument('--step-freq-full', action='store', type=float, default=FULL_SCAN_FREQ_STEP, dest='full_scan_freq_step', help='step size of the switching-frequency to use for a full total capacitance scan. (default: %(default)s)')
    scan_argument_group.add_argument('--max-freq-cv', action='store', type=float, default=MAXIMUM_CV_FREQ, dest='maximum_cv_freq', help='Maximum switching-frequency to use for capacitance scans in order to characterize the sensors C-V behaviour. (default: %(default)s)')
    scan_argument_group.add_argument('--step-freq-cv', action='store', type=float, default=CV_FREQ_STEP, dest='cv_freq_step', help='step size of the switching-frequency to use for capacitance scans in order to characterize the sensors C-V behaviour. (default: %(default)s)')
    scan_argument_group.add_argument('--step-leakage-hv', action='store', type=float, default=HV_STEP, dest='hv_step', help='Voltage step size to scan the leakage current and C-V behaviour of the sensor using reversed bias. (default: %(default)s)')
    scan_argument_group.add_argument('--max-leakage-hv', action='store', type=float, default=MAXIMUM_HV_VOLTAGE, dest='maximum_hv_voltage', help='Maximum voltage to use for leakage current measurements using reversed bias. For fine grained measurements currently a hardcoded grid is used. In this case this value is used as a safe-guard to protect the connected sensor. The value needs to be positive-definit. (default: %(default)s)')
    scan_argument_group.add_argument('--max-freq-inter', action='store', type=float, default=MAXIMUM_INTER_PIX_FREQ, dest='maximum_inter_pix_freq', help='Maximum switching-frequency to use for a full inter-pixel capacitance scan. (default: %(default)s)')
    scan_argument_group.add_argument('--step-freq-inter', action='store', type=float, default=INTER_PIX_FREQ_STEP, dest='inter_pix_freq_step', help='step size of the switching-frequency to use for a full inter-pixel capacitance scan. (default: %(default)s)')

    arguments = argument_parser.parse_args()

    print(type(arguments.wait))
    print(arguments.wait)
    print(type(arguments.hv_voltage))

    rounded = int(arguments.hv_voltage)
    if np.abs(arguments.hv_voltage - rounded) < 0.05:
        arguments.hv_voltage = rounded

    print(arguments.hv_voltage)
    print(type(arguments.freq_settle))
    print(arguments.freq_settle)
    print("biased_{}_V_full".format(arguments.hv_voltage))
    print("inter_biased_M_{}_V_full".format(arguments.hv_voltage))

    if arguments.verbose_flag:
        logging.root.setLevel(logging.DEBUG)

    # initial measurement sample
    perform_initial_total_measurement(arguments)

    # completing scan
    perform_biased_total_cap(arguments)

    # I-V characterization!
    perform_iv_measurement(arguments)

    # C-V characterization sample
    coarse_bias_range = -1 * np.arange(0.1, arguments.maximum_hv_voltage, arguments.hv_step)
    # fine grid for HPK sensors.
    # fine_bias_range = -1 * np.unique(np.concat((
    #     np.geomspace(0.1, 1, 8),
    #     np.geomspace(1, 15, 14),
    #     np.arange(15, 50.1, 5),
    #     np.geomspace(50,150, 26),
    #     np.arange(150, 350,10)
    # )))
    # fine grid sintef
    # fine_bias_range = -1 * np.unique(np.concat((
    #     np.geomspace(0.1, 30, 30),
    #     np.geomspace(30, 58, 41)
    # )))
    # fine grid FBK
    fine_bias_range = -1 * np.unique(np.concat((
        np.geomspace(0.1, 15, 15),
        np.geomspace(15, 40, 20),
        np.arange(40, 130.1, 1.25),
    )))
    # fine grid R11/R13/R1
    # fine_bias_range = -1 * np.unique(np.concat((
    #     np.geomspace(0.1, 30, 20),
    #     np.arange(30, 160.1, 2)
    # )))

    # coarse scan
    perform_coarse_cv_scan(arguments, coarse_bias_range)

    # fine scan
    perform_fine_cv_scan(arguments, fine_bias_range[np.abs(fine_bias_range) < arguments.maximum_hv_voltage])

    # perform the inter-pixel cap scans
    scan_configuration[ScanConfigurationKeys.AVERAGE_MEASUREMENTS] = 40
    perform_inter_pix_scan(arguments)


if __name__ == "__main__":
    main()
